# Generated by Django 5.0.6 on 2024-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tournament_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
